// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.model;

import com.nanuvem.lom.model.PropertyDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PropertyDataOnDemand_Roo_Configurable {
    
    declare @type: PropertyDataOnDemand: @Configurable;
    
}
