// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.model;

import com.nanuvem.lom.model.PropertyValueDataOnDemand;
import com.nanuvem.lom.model.PropertyValueIntegrationTest;
import com.nanuvem.lom.service.PropertyValueService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PropertyValueIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PropertyValueIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PropertyValueIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PropertyValueIntegrationTest: @Transactional;
    
    @Autowired
    private PropertyValueDataOnDemand PropertyValueIntegrationTest.dod;
    
    @Autowired
    PropertyValueService PropertyValueIntegrationTest.propertyValueService;
    
    @Test
    public void PropertyValueIntegrationTest.testCountAllPropertyValues() {
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", dod.getRandomPropertyValue());
        long count = propertyValueService.countAllPropertyValues();
        Assert.assertTrue("Counter for 'PropertyValue' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PropertyValueIntegrationTest.testFindPropertyValue() {
        PropertyValue obj = dod.getRandomPropertyValue();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to provide an identifier", id);
        obj = propertyValueService.findPropertyValue(id);
        Assert.assertNotNull("Find method for 'PropertyValue' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'PropertyValue' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PropertyValueIntegrationTest.testFindAllPropertyValues() {
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", dod.getRandomPropertyValue());
        long count = propertyValueService.countAllPropertyValues();
        Assert.assertTrue("Too expensive to perform a find all test for 'PropertyValue', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<PropertyValue> result = propertyValueService.findAllPropertyValues();
        Assert.assertNotNull("Find all method for 'PropertyValue' illegally returned null", result);
        Assert.assertTrue("Find all method for 'PropertyValue' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PropertyValueIntegrationTest.testFindPropertyValueEntries() {
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", dod.getRandomPropertyValue());
        long count = propertyValueService.countAllPropertyValues();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<PropertyValue> result = propertyValueService.findPropertyValueEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'PropertyValue' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'PropertyValue' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PropertyValueIntegrationTest.testFlush() {
        PropertyValue obj = dod.getRandomPropertyValue();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to provide an identifier", id);
        obj = propertyValueService.findPropertyValue(id);
        Assert.assertNotNull("Find method for 'PropertyValue' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPropertyValue(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'PropertyValue' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropertyValueIntegrationTest.testUpdatePropertyValueUpdate() {
        PropertyValue obj = dod.getRandomPropertyValue();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to provide an identifier", id);
        obj = propertyValueService.findPropertyValue(id);
        boolean modified =  dod.modifyPropertyValue(obj);
        Integer currentVersion = obj.getVersion();
        PropertyValue merged = propertyValueService.updatePropertyValue(obj);
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'PropertyValue' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropertyValueIntegrationTest.testSavePropertyValue() {
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", dod.getRandomPropertyValue());
        PropertyValue obj = dod.getNewTransientPropertyValue(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'PropertyValue' identifier to be null", obj.getId());
        propertyValueService.savePropertyValue(obj);
        obj.flush();
        Assert.assertNotNull("Expected 'PropertyValue' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PropertyValueIntegrationTest.testDeletePropertyValue() {
        PropertyValue obj = dod.getRandomPropertyValue();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'PropertyValue' failed to provide an identifier", id);
        obj = propertyValueService.findPropertyValue(id);
        propertyValueService.deletePropertyValue(obj);
        obj.flush();
        Assert.assertNull("Failed to remove 'PropertyValue' with identifier '" + id + "'", propertyValueService.findPropertyValue(id));
    }
    
}
