// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.model;

import com.nanuvem.lom.model.PropertyValue;

privileged aspect PropertyValue_Roo_JavaBean {
    
    public String PropertyValue.get_value() {
        return this._value;
    }
    
    public void PropertyValue.set_value(String _value) {
        this._value = _value;
    }
    
}
