// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.dao.typesquare;

import com.nanuvem.lom.dao.typesquare.EntityDataOnDemand;
import com.nanuvem.lom.dao.typesquare.EntityIntegrationTest;
import org.junit.Assert;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect EntityIntegrationTest_Roo_IntegrationTest {
    
    declare @type: EntityIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: EntityIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: EntityIntegrationTest: @Transactional;
    
    @Autowired
    private EntityDataOnDemand EntityIntegrationTest.dod;
    
}
