// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.model;

import com.nanuvem.lom.dao.PropertyDAO;
import com.nanuvem.lom.model.PropertyDataOnDemand;
import com.nanuvem.lom.model.PropertyIntegrationTest;
import com.nanuvem.lom.service.PropertyService;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PropertyIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PropertyIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PropertyIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PropertyIntegrationTest: @Transactional;
    
    @Autowired
    private PropertyDataOnDemand PropertyIntegrationTest.dod;
    
    @Autowired
    PropertyService PropertyIntegrationTest.propertyService;
    
    @Autowired
    PropertyDAO PropertyIntegrationTest.propertyDAO;
    
    @Test
    public void PropertyIntegrationTest.testCountAllPropertys() {
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", dod.getRandomProperty());
        long count = propertyService.countAllPropertys();
        Assert.assertTrue("Counter for 'Property' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PropertyIntegrationTest.testFindProperty() {
        Property obj = dod.getRandomProperty();
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Property' failed to provide an identifier", id);
        obj = propertyService.findProperty(id);
        Assert.assertNotNull("Find method for 'Property' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Property' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PropertyIntegrationTest.testFindAllPropertys() {
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", dod.getRandomProperty());
        long count = propertyService.countAllPropertys();
        Assert.assertTrue("Too expensive to perform a find all test for 'Property', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Property> result = propertyService.findAllPropertys();
        Assert.assertNotNull("Find all method for 'Property' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Property' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PropertyIntegrationTest.testFindPropertyEntries() {
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", dod.getRandomProperty());
        long count = propertyService.countAllPropertys();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Property> result = propertyService.findPropertyEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Property' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Property' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PropertyIntegrationTest.testFlush() {
        Property obj = dod.getRandomProperty();
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Property' failed to provide an identifier", id);
        obj = propertyService.findProperty(id);
        Assert.assertNotNull("Find method for 'Property' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyProperty(obj);
        Integer currentVersion = obj.getVersion();
        propertyDAO.flush();
        Assert.assertTrue("Version for 'Property' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropertyIntegrationTest.testUpdatePropertyUpdate() {
        Property obj = dod.getRandomProperty();
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Property' failed to provide an identifier", id);
        obj = propertyService.findProperty(id);
        boolean modified =  dod.modifyProperty(obj);
        Integer currentVersion = obj.getVersion();
        Property merged = propertyService.updateProperty(obj);
        propertyDAO.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Property' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PropertyIntegrationTest.testSaveProperty() {
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", dod.getRandomProperty());
        Property obj = dod.getNewTransientProperty(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Property' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Property' identifier to be null", obj.getId());
        propertyService.saveProperty(obj);
        propertyDAO.flush();
        Assert.assertNotNull("Expected 'Property' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PropertyIntegrationTest.testDeleteProperty() {
        Property obj = dod.getRandomProperty();
        Assert.assertNotNull("Data on demand for 'Property' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Property' failed to provide an identifier", id);
        obj = propertyService.findProperty(id);
        propertyService.deleteProperty(obj);
        propertyDAO.flush();
        Assert.assertNull("Failed to remove 'Property' with identifier '" + id + "'", propertyService.findProperty(id));
    }
    
}
