// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nanuvem.lom.business.dao;

import com.nanuvem.lom.business.dao.Clazz;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Clazz_Roo_Configurable {
    
    declare @type: Clazz: @Configurable;
    
}
